# -*- coding: utf-8 -*-
"""reader_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qdg8oQXBHaJfB_tgB-JdPIJfylldNbqD
"""

import requests
import os
def get_surah_text(surah):
    url = f"https://quranapi.pages.dev/api/{surah}.json"
    response = requests.get(url)
    if response.status_code != 200:
        print("فشل في جلب الآية.")
        return None
    data = response.json()
    data =  data.get("surahNameArabic"),data.get("arabic1")
    for idx,i in enumerate(data[1]):
      print(f"{i} {idx+1}")

def get_ayah_text(surah,ayah):
    url = f"https://quranapi.pages.dev/api/{surah}/{ayah}.json"
    response = requests.get(url)
    if response.status_code != 200:
        print("فشل في جلب الآية.")
        return None
    data = response.json()
    data = data.get("surahNameArabic"),data.get("arabic1")
    print(data[0])
    print(data[1],ayah)

def get_audio_text(surah,ayah):
    url = f"https://quranapi.pages.dev/api/{surah}/{ayah}.json"
    response = requests.get(url)
    if response.status_code != 200:
        print("فشل في جلب الآية.")
        return None
    data = response.json()
    surahName = data.get("surahName")
    audio = data.get("audio",{}).get("1")
    audio_url = audio.get("url")
    reciter_name = audio.get("reciter", "قارئ غير معروف")
    print(f"🔹 السورة: {surahName}")
    print(f"🔊 القارئ: {reciter_name}")
    print(f"🎧 يتم تشغيل الآية {ayah} من السورة رقم {surah}...")
    return audio_url
def play_sound(url):
  from IPython.display import Audio
  display(Audio(url, autoplay=True))
#get_surah_text(1)
#get_ayah_text(2,1)
#play_sound(get_audio_text(2,1))